# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "hsh-thesis"
version = "1.0.0"
entrypoint = "src/lib.typ"
authors = ["Tobias Wylega <https://github.com/MrToWy>"]
license = "Unlicense"
description = ""
homepage = ""
repository = ""
keywords = ["thesis", "hsh", "Hochschule Hannover"]
categories = ["thesis"]
disciplines = []
compiler = "0.11.1"
exclude = [
	".github",
	"docs",
	"scripts",
	"tests",
	".typstignore",
	"Justfile",
]

[template]
path = "template"
entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
